// <auto-generated />
using System;
using MellArguello_EXAMENP1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MellArguello_EXAMENP1.Migrations
{
    [DbContext(typeof(MellArguello_EXAMENP1Context))]
    [Migration("20241028160842_BorrarOtraFecha3")]
    partial class BorrarOtraFecha3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MellArguello_EXAMENP1.Models.MA_Burger", b =>
                {
                    b.Property<int>("MA_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MA_Id"));

                    b.Property<bool>("MA_ConsumidorFinal")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MA_Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("MA_Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("MA_Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MA_Id");

                    b.ToTable("MA_Burger");
                });
#pragma warning restore 612, 618
        }
    }
}
