// <auto-generated />
using System;
using MellArguello_EXAMENP1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MellArguello_EXAMENP1.Migrations
{
    [DbContext(typeof(MellArguello_EXAMENP1Context))]
    partial class MellArguello_EXAMENP1ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MellArguello_EXAMENP1.Models.MA_Burger", b =>
                {
                    b.Property<string>("MA_Nombre")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("MA_ConsumidorFinal")
                        .HasMaxLength(50)
                        .HasColumnType("bit");

                    b.Property<DateTime>("MA_Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("MA_Id")
                        .HasColumnType("int");

                    b.Property<decimal>("MA_Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OtraFecha")
                        .HasColumnType("datetime2");

                    b.HasKey("MA_Nombre");

                    b.ToTable("MA_Burger");
                });
#pragma warning restore 612, 618
        }
    }
}
